#!/bin/bash
clear
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
tyblue='\e[1;36m'
NC='\e[0m'
purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
lastest_version="$(curl -s https://api.github.com/repos/vernesong/OpenClash/releases | grep tag_name | sed -E 's/.*"v(.*)".*/\1/' | head -n 1)"
clear

echo -e "  ************************************************"
echo -e "         Installer OpenClash Mod by ARF.PRSTY "
echo -e "  ************************************************"
echo -e " "
echo -e "Notes : "
echo -e "- Installer ini akan menghapus semua data yang ada di Openclash sebelumnya."
echo -e "- Pastikan anda telah mem-backup data config dan data penting openclash anda."
echo -e "- Saya tidak bertanggung jawab atas hilang nya semua data Openclash"
echo -e "- Termasuk semua data config & data rules & data proxies."
sleep 5
echo -e " "
echo -e "Installer ini akan menggantikan semua data sebelumnya ke versi Terbaru :"
echo -e "- OpenClash_$lastest_version MOD by ARF.PRSTY"
echo -e "- Include Proxies LIVE.ON"
echo -e "- Include Proxies TSEL-ILPED"
echo -e "- Include Config Single Modem"
echo -e "- Include Config Dual Modem / Loadbalance"
echo -e "- Include Simple Rules / Pisah Trafic"
echo -e "- Include Adguard DNS"
echo -e "- Include YACD PANEL TAB"
echo -e "- Include Config Editor ( Tinyfm )"
echo -e ""
echo -e " Proses peng-installan bisa lebih lama dari perkiraan, pastikan koneksi internet stabil!..."
echo -e ""
echo -e "  ************************************************"
echo -e "         Installer IPK.MOD Mod by ARF.PRSTY "
echo -e "  ************************************************"
echo -e ""
read -n 1 -s -r -p "Tekan ENTER untuk melanjutkan / CTRL + C untuk membatalkan"
sleep 2

cd /root
echo -e ""
echo -e ""
echo -e " Meng-update seluruh data Package ..."
echo -e " "
opkg update

echo -e " "
echo -e " "
echo -e " Menghapus file lama Openclash ..."
echo -e " "
opkg remove --force-depends luci-app-openclash
sleep 2
rm -rf /tmp/luci*
sleep 2
rm -rf /usr/lib/lua/luci/model/cbi/openclash*
sleep 2
rm -rf /usr/lib/lua/luci/view/openclash*
sleep 2
rm -rf /usr/lib/lua/luci/view/controller/openclash*
sleep 2
rm -rf /www/luci-static/resources/openclash*
sleep 2
rm -rf /tmp/openclash*
sleep 2
rm -rf /tmp/clash*
sleep 2
rm -rf /tmp/luci*
sleep 2

echo -e " "
echo -e " "
echo -e " Meng-update seluruh data Package ..."
echo -e " "
opkg update


mkdir /root/luci-app-arf/
cd /root/luci-app-arf/
sleep 2
echo -e " "
echo -e " "
echo -e " Meng-install Openclash Terbaru ..."
echo -e " "
wget https://github.com/vernesong/OpenClash/raw/master/luci-app-openclash_${lastest_version}_all.ipk
sleep 2
opkg install --force-depends *.ipk
sleep 2

echo -e " "
echo -e " "
echo -e " Membuat file Mod Openclash..."
echo -e " "
rm -rvf /etc/openclash*
wget https://github.com/arfprsty810/luci-app-arf/raw/main/luci-app-openclash/config-oc/etc.zip
wget https://github.com/arfprsty810/luci-app-arf/raw/main/luci-app-openclash/config-oc/usr.zip
wget https://github.com/arfprsty810/luci-app-arf/raw/main/luci-app-openclash/config-oc/www.zip
sleep 2
unzip etc.zip -d /etc/ -A
unzip usr.zip -d /usr/ -A
unzip www.zip -d /www/ -A
sleep 2

cd /root
echo -e " "
echo -e " "
echo -e " Membersihkan File-file yang sudah tidak terpakai ..."
echo -e " "
rm -rvf /root/luci-app-arf*
sleep 2
rm -rf /usr/bin/luci-arf*
sleep 2
rm -rf /tmp/luci*
sleep 2
echo -e " "
echo -e " "
echo -e "Finished ..."
echo -e " "
sleep 2

echo -e " "
echo -e " "
echo -e " Installasi sudah selesai, Openclash sudah bisa dapat dijalankan ^_^ ..."
echo -e ""
read -n 1 -s -r -p "Pencet tombol apa saja untuk keluar & kembali"
clear
exit
