#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
yell='\e[1;33m'
tyblue='\e[1;36m'
NC='\e[0m'
purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'

# // Export Banner Status Information
export EROR="[${RED} EROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"
clear

f_oc="/etc/openclash"
oc="luci-app-openclash"
rule_oc="/rule_provider"
luci="/usr/lib/lua/luci/view/openclash"
lucic="/usr/lib/lua/luci/controller"
luci_static="/www/luci-static/resources/openclash/img"
api_oc="api.github.com/repos/vernesong/OpenClash/releases"
download_oc="github.com/vernesong/OpenClash/releases/download"
arfprsty810="raw.githubusercontent.com/d-jumper/luci-app-arf/main/${oc}"
lastest_version="$(curl -s "https://${api_oc}" | grep tag_name | sed -E 's/.*"v(.*)".*/\1/' | head -n 1)"
clear

echo -e "\033[0;34m┌─────────────────────────────────────────────────────┐${NC}"
echo -e "             ⇱ \e[32;1mAuto Installer Openclash Mod\e[0m ⇲ "
echo -e "\033[0;34m└─────────────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "  ${INFO}\e[32;1m Notes :\e[32;1m "
echo -e "${NC}-${CYAN} Installer ini akan menghapus semua data yang ada di Openclash sebelumnya. ${NC}"
echo -e "${NC}-${CYAN} Pastikan anda telah mem-backup data config dan data penting openclash anda. ${NC}"
echo -e "${NC}-${CYAN} Saya tidak bertanggung jawab atas hilang nya semua data Openclash anda. ${NC}"
echo -e "${NC}-${CYAN} Termasuk semua data config & data rules & data proxies. ${NC}"
echo -e ""
echo -e "  ${INFO}\e[32;1m Installer ini akan menggantikan semua data sebelumnya ke versi Terbaru :\e[32;1m"
echo -e "${NC}-${CYAN} OpenClash_${lastest_version} ${NC}"
echo -e "${NC}-${CYAN} MOD Smooth GUI ${NC}"
echo -e "${NC}-${CYAN} Include Proxies LIVE.ON ${NC}"
echo -e "${NC}-${CYAN} Include Proxies TSEL-ILPED ${NC}"
echo -e "${NC}-${CYAN} Include Config Single Modem ${NC}"
echo -e "${NC}-${CYAN} Include Config Dual Modem / Loadbalance ${NC}"
echo -e "${NC}-${CYAN} Include Simple Rules / Pisah Trafic ${NC}"
echo -e "${NC}-${CYAN} Include Adguard DNS ${NC}"
echo -e "${NC}-${CYAN} Include YACD PANEL TAB ${NC}"
echo -e "${NC}-${CYAN} Include Config Editor ( Tinyfm ) ${NC}"
echo -e ""
echo -e " ${INFO}\e[32;1m Proses peng-installan bisa lebih lama dari waktu perkiraan.\e[32;1m"
echo -e " ${INFO}\e[32;1m Update ini memerlukan koneksi jaringan internet.\e[32;1m" 
echo -e " ${INFO}\e[32;1m Pastikan koneksi jaringan internet stabil.\e[32;1m"
echo -e ""
echo -e "\033[0;34m┌─────────────────────────────────────────────────────┐${NC}"
echo -e "             ⇱ \e[32;1mAuto Installer Openclash Mod\e[0m ⇲ "
echo -e "\033[0;34m└─────────────────────────────────────────────────────┘${NC}"
echo -e ""
read -n 1 -s -r -p "Tekan ENTER untuk melanjutkan / CTRL + C untuk membatalkan"
sleep 2
clear

echo -e "\033[0;34m┌─────────────────────────────────────────────────────┐${NC}"
echo -e "             ⇱ \e[32;1mAuto Installer Openclash Mod\e[0m ⇲ "
echo -e "\033[0;34m└─────────────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "${INFO}\e[32;1m Proses Instalasi sedang berlangsung, mohon tunggu hingga selesai."
echo -e ""

cd /root
mkdir -p /root/luci-app-arf/ >/dev/null 2>&1
cd /root/luci-app-arf/ 2>&1
wget "https://${download_oc}/v${lastest_version}/${oc}_${lastest_version}_all.ipk" >/dev/null 2>&1
wget "https://${arfprsty810}/${oc}.zip" >/dev/null 2>&1
#opkg remove --force-depends ${oc} >/dev/null 2>&1
opkg install --force-depends *.ipk >/dev/null 2>&1
sleep 2
echo -e "${OKEY}${NC} ${CYAN} Berhasil Meng-install Openclash Terbaru ...${NC}"

rm -rvf ${f_oc}/backup/*
rm -rvf ${f_oc}/config/*
rm -rvf ${f_oc}/core/*
rm -rvf ${f_oc}/game_rules/*
rm -rvf ${f_oc}/proxy_provider/*
rm -rvf ${f_oc}${rule_oc}/*
rm -rvf ${f_oc}/*.conf >/dev/null 2>&1
rm -rvf ${f_oc}/*.ipset >/dev/null 2>&1
rm -rvf ${f_oc}/*.mmdb >/dev/null 2>&1
rm -rvf ${f_oc}/*.dat >/dev/null 2>&1
unzip -o luci-app-openclash.zip -d / 2>&1

sleep 2
chmod 755 ${f_oc}/backup/* >/dev/null 2>&1
chmod 755 ${f_oc}/config/* >/dev/null 2>&1
chmod 755 ${f_oc}/core/* >/dev/null 2>&1
chmod 755 ${f_oc}/game_rules/* >/dev/null 2>&1
chmod 755 ${f_oc}/proxy_provider/* >/dev/null 2>&1
chmod 755 ${f_oc}${rule_oc}/* >/dev/null 2>&1
chmod 755 ${f_oc}/*.conf >/dev/null 2>&1
chmod 755 ${f_oc}/*.ipset >/dev/null 2>&1
chmod 755 ${f_oc}/*.mmdb >/dev/null 2>&1
chmod 755 ${f_oc}/*.dat >/dev/null 2>&1
chmod 755 /etc/config/openclash 2>&1
chmod 755 ${lucic}/openclash.lua 2>&1
chmod 755 ${luci}/*.htm 2>&1
chmod 755 ${luci_static}/Sponsor.svg 2>&1
chmod 755 ${luci_static}/Star.svg 2>&1
chmod 755 ${luci_static}/Star.svg 2>&1
chmod 755 ${luci_static}/Tutorials.svg 2>&1
chmod 755 ${luci_static}/Wiki.svg 2>&1
chmod 755 ${luci_static}/arrow-clockwise-light.svg 2>&1
chmod 755 ${luci_static}/eye-light.svg 2>&1
chmod 755 ${luci_static}/eye-slash-light.svg 2>&1
chmod 755 ${luci_static}/logo.png 2>&1
chmod 755 ${luci_static}/meta.png 2>&1
chmod 755 ${luci_static}/wrench-light.svg 2>&1
sleep 2
echo -e "${OKEY}${NC} ${CYAN} Berhasil Menginstall file MOD ...${NC}"
sleep 1
echo -e "${OKEY}${NC} ${CYAN} Berhasil Membersihkan File-file yang sudah tidak terpakai ...${NC}"

cd /root 2>&1
rm -rvf /root/luci-app-arf* >/dev/null 2>&1
rm -rf /usr/bin/${oc}* >/dev/null 2>&1
rm -rf /tmp/luci* >/dev/null 2>&1
echo -e "${OKEY}${NC} ${CYAN} Berhasil Membersihkan File-file yang sudah tidak terpakai ...${NC}"
sleep 2
echo -e "${OKEY}${NC} ${CYAN}Finished ...${NC}"
echo -e ""
echo -e ""
/etc/init.d/openclash restart openclash
/etc/init.d/openclash start openclash
sleep 2
echo -e ""
echo -e ""
echo -e "${INFO}\e[32;1m Installasi sudah selesai.\e[32;1m"
echo -e "${INFO}\e[32;1m Hapus cache browser & Release Ram.\e[32;1m"
echo -e "${INFO}\e[32;1m Openclash sudah bisa dapat dijalankan ^_^ ...\e[32;1m"
echo -e ""
read -n 1 -s -r -p "Pencet tombol apa saja untuk keluar & kembali"
clear
exit
