#!/bin/bash
clear
echo -e "  ************************************************"
echo -e "         Installer OpenClash Mod by ARF.PRSTY "
echo -e "  ************************************************"
echo -e " "
echo -e "Notes : "
echo -e "- Installer ini akan menghapus semua data yang ada di Openclash sebelumnya."
echo -e "- Pastikan anda telah mem-backup data config dan data penting openclash anda."
echo -e "- Saya tidak bertanggung jawab atas hilang nya semua data Openclash"
echo -e "- Termasuk semua data config & data rules & data proxies."
sleep 5
echo -e " "
echo -e "Installer ini akan menggantikan semua data sebelumnya ke versi Terbaru :"
echo -e "- OpenClash_0.45.129-beta MOD by ARF.PRSTY"
echo -e "- Include Proxies LIVE.ON"
echo -e "- Include Proxies TSEL-ILPED"
echo -e "- Include Config Single Modem"
echo -e "- Include Config Dual Modem / Loadbalance"
echo -e "- Include Simple Rules / Pisah Trafic"
echo -e "- Include Adguard DNS"
echo -e "- Include YACD PANEL TAB"
echo -e "- Include Config Editor ( Tinyfm )"
echo -e ""
echo -e " Proses peng-installan bisa lebih lama dari perkiraan, pastikan koneksi internet stabil!..."
echo -e ""
echo -e "  ************************************************"
echo -e "         Installer IPK.MOD Mod by ARF.PRSTY "
echo -e "  ************************************************"
echo -e ""
read -n 1 -s -r -p "Tekan ENTER untuk melanjutkan / CTRL + C untuk membatalkan"
sleep 2
echo -e ""

cd /root
opkg update
opkg remove --force-depends luci-app-openclash
sleep 2
rm -rf /tmp/luci*
sleep 2
rm -rf /usr/lib/lua/luci/model/cbi/openclash
sleep 2
rm -rf /usr/lib/lua/luci/view/openclash
sleep 2
rm -rf /www/luci-static/resources/openclash
sleep 2
rm -rf /tmp/openclash*
sleep 2
rm -rf /tmp/clash*
sleep 2
rm -rf /tmp/luci*
sleep 2

cd /root
opkg update
sleep 2

wget https://raw.githubusercontent.com/arfprsty810/luci-app-arf/main/luci-app-openclash/luci-arf-openclash_0.45.129-beta.ipk
sleep 2
opkg install --force-depends *.ipk
sleep 2

cd /root
rm -rf *.ipk
sleep 2
rm -rf /usr/bin/luci-arf*
sleep 2
rm -rf /tmp/luci*
sleep 2
echo -e "Finished ..."
sleep 2

echo -e ""
echo -e ""
echo -e " Installasi sudah selesai, Openclash sudah bisa dapat dijalankan ^_^ ..."
echo -e ""
read -n 1 -s -r -p "Pencet tombol apa saja untuk keluar & kembali"
clear
exit
